

#define DEFINE_DYNAMIC_SIZED_STACK(DYNAMIC_SIZED_STACK_NAME, DYNAMIC_SIZED_STACK_PREFIX, DYNAMIC_SIZED_STACK_ELEMENT) \
struct DYNAMIC_SIZED_STACK_NAME ## _Block_Header; \
typedef struct { \
  DYNAMIC_SIZED_STACK_NAME ## _Block_Header *next; \
} DYNAMIC_SIZED_STACK_NAME ## _Block_Header; \
\
typedef struct { \
} DYNAMIC_SIZED_STACK_NAME;