#!/bin/bash
SCRIPT_DIR=$(dirname $0)

#Common directories used by various scripts
CODE_DIRECTORY=$SCRIPT_DIR/../code
INTERMEDIATE_DIRECTORY=$SCRIPT_DIR/../intermediate
KERNEL_SOURCE_DIRECTORY=$SCRIPT_DIR/../src
TOOLS_SOURCE_DIRECTORY=$CODE_DIRECTORY/tools
COMMON_SOURCE_DIRECTORY=$CODE_DIRECTORY/common
BINARY_OUTPUT_DIRECTORY=$INTERMEDIATE_DIRECTORY/binaries
IMAGE_OUTPUT_DIRECTORY=$INTERMEDIATE_DIRECTORY/images
LOG_OUTPUT_DIRECTORY=$INTERMEDIATE_DIRECTORY/log

#GRUB configuration
GRUB_CONFIG_FILE=$SCRIPT_DIR/../miscellaneous/grub.cfg

#QEMU configuration
QEMU_EXECUTABLE=qemu-system-x86_64.exe
QEMU_MEMORY_IN_MB=1024
QEMU_CPU_CORE_COUNT=1